config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render 'New'
    end
  end

  def show
    @task = Task.find(params[:id])
  end


  private

  def task_params
    params.require(:task).permit(:title, :description, :company, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rabbit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.haml
.container
  %h2 Create a new task
  = simple_form_for @task do |f|
    = f.input :title, label: "Title"
    = f.input :description, label: "Description"
    = f.input :company, label: "Company"
    = f.input :url, label: "Link to Task"
    = f.button :submit

  %br
  .btn.btn-info
    =link_to "All Task", tasks_path

app/views/tasks/index.html.haml
:css
  .btn a {
    color:#fff;
    text-decoration:none;
  }
  .time_align{
    text-align:center;
  }

%h1{style:"text-align:center"} List all the Tasks.
.container
  -@tasks.each do |task|
    %h4=task.title
    %h4=task.description
    %h4=task.company
    %h4=task.url
    %h5.time_align="Create at #{task.created_at}."
    %br
  .btn.btn-info
    =link_to "New Task", new_task_path

app/views/tasks/new.html.haml
=render 'form'

app/views/tasks/show.html.haml
:css
  .btn a {
    color:#fff;
    text-decoration:none;
  }

.container
  %h3="task #{@task.id} is shown in details"
  %br
  %h4=@task.title
  %h4=@task.description
  %h4=@task.company
  %h4=@task.url

  .btn.btn-info
    =link_to "New Task", new_task_path
  .btn.btn-info
    =link_to "All Task", tasks_path